# Linear Regression Assignment #

In [10]:
# import the libraries:
import pandas as pd
dataset=pd.read_csv('insurance_pre.csv')
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [11]:
dataset.age.dtype

dtype('int64')

In [12]:
dataset.smoker.dtype

dtype('O')

In [13]:
dataset.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
charges     0
dtype: int64

In [14]:
dataset.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges'], dtype='object')

In [15]:
# Pre_Processing the Dataset:
# Convert Categorical value into numerical value:
dataset = pd.get_dummies(dataset,drop_first=True)
dataset = dataset.astype(int)
dataset.head()

   age  bmi  children  charges  sex_male  smoker_yes
0   19   27         0    16884         0           1
1   18   33         1     1725         1           0
2   28   33         3     4449         1           0
3   33   22         0    21984         1           0
4   32   28         0     3866         1           0

In [16]:
# Split input output columns:
independent = dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [17]:
dependent = dataset[['charges']]

In [18]:
# Split train and test:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [19]:
# Standardization:
#In simple linear regression's Coefficients are affected by feature scale. so, i am going to do StandardScaler.
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [20]:
# import Linear Regression model
from sklearn.linear_model import LinearRegression
# name the model:
regressor = LinearRegression()
# train the model:
regressor = regressor.fit(x_train,y_train)
regressor
# here model trained.

LinearRegression()

In [21]:
regressor.coef_

array([[3612.71085379, 2003.91498519,  570.98161938,  -19.88712653,
        9425.27580509]])

In [22]:
regressor.intercept_

array([13232.42521368])

In [23]:
# training predicted output:
y_train_predict = regressor.predict(x_train)
y_train_predict

array([[ 1.72019667e+03],
       [ 8.41852481e+03],
       [ 1.86283373e+04],
       [ 7.78646789e+03],
       [ 6.17828949e+03],
       [ 2.29846090e+03],
       [ 2.66921561e+04],
       [ 1.43741036e+04],
       [ 1.06900816e+04],
       [ 1.62335962e+04],
       [ 1.22378243e+04],
       [ 1.11486673e+04],
       [ 3.96438053e+04],
       [ 6.05732482e+03],
       [ 1.18881102e+04],
       [ 3.41520411e+03],
       [ 1.50009097e+04],
       [ 4.69643250e+03],
       [ 4.94540361e+03],
       [ 5.56388183e+03],
       [ 1.55618600e+04],
       [ 9.14405369e+03],
       [ 8.53766858e+03],
       [ 3.44932200e+04],
       [ 6.68373213e+03],
       [ 2.68254133e+04],
       [ 2.70883919e+04],
       [ 1.55844247e+04],
       [ 8.62268925e+03],
       [ 3.43067983e+04],
       [ 1.04198319e+04],
       [ 3.91711092e+03],
       [ 1.55343673e+04],
       [ 2.99484850e+04],
       [ 2.98725563e+04],
       [ 2.81446060e+04],
       [ 9.65451777e+03],
       [ 3.25438847e+04],
       [ 4.26873944e+03],
       [ 2.55026847e+04],
       [ 5.44773917e+03],
       [ 2.82815985e+04],
       [ 7.28476051e+03],
       [ 1.46426383e+04],
       [ 2.68111796e+03],
       [ 3.51234560e+04],
       [ 1.51310598e+04],
       [ 3.66791049e+03],
       [ 1.25271836e+03],
       [ 9.99567467e+03],
       [ 9.61301761e+03],
       [ 1.09271889e+04],
       [ 1.70197601e+04],
       [ 4.43302518e+03],
       [ 2.43171810e+03],
       [ 4.14586041e+03],
       [ 5.47714624e+03],
       [ 6.02044723e+03],
       [ 2.70124632e+04],
       [ 1.41664033e+04],
       [ 1.20647819e+04],
       [ 8.39413918e+03],
       [ 1.39205393e+04],
       [ 2.51663278e+03],
       [ 1.30428177e+04],
       [ 1.12248253e+04],
       [ 1.93311780e+03],
       [ 9.77447267e+02],
       [ 3.67458413e+04],
       [ 7.94057489e+03],
       [ 8.83914621e+03],
       [ 2.07846810e+03],
       [ 1.18514320e+04],
       [ 8.27488944e+03],
       [ 1.23587890e+04],
       [ 2.54109277e+04],
       [ 2.75992847e+04],
       [ 8.26943925e+03],
       [ 7.57876762e+03],
       [ 5.53290037e+02],
       [ 4.54734694e+03],
       [ 7.41428245e+03],
       [ 3.25938219e+03],
       [ 8.46504642e+03],
       [ 1.97815380e+03],
       [ 4.57857491e+03],
       [ 3.37212629e+04],
       [ 6.52780422e+03],
       [ 1.14450175e+04],
       [ 9.49558876e+03],
       [ 3.15792281e+04],
       [ 1.10588246e+04],
       [ 1.09895389e+04],
       [ 5.06154628e+03],
       [ 6.93131108e+03],
       [ 5.20901036e+03],
       [ 5.01673959e+03],
       [ 1.01514966e+04],
       [ 3.12486489e+04],
       [ 3.01671869e+03],
       [ 3.76132906e+04],
       [ 1.03471038e+04],
       [ 9.40885317e+03],
       [ 2.62732526e+03],
       [ 1.14970953e+04],
       [ 3.04960560e+04],
       [ 2.45428282e+03],
       [ 6.43624662e+03],
       [ 1.12162680e+04],
       [ 1.02744816e+04],
       [ 5.56388183e+03],
       [ 1.26393109e+04],
       [ 1.17269315e+04],
       [ 2.83871635e+04],
       [ 1.12957325e+04],
       [ 1.09480387e+04],
       [ 1.48900178e+04],
       [ 1.23673463e+04],
       [ 2.83162563e+04],
       [ 1.14639530e+04],
       [ 1.27016608e+04],
       [ 1.53750095e+04],
       [ 3.81497571e+03],
       [ 2.85689627e+04],
       [ 9.12340332e+03],
       [ 2.87869351e+04],
       [ 1.13203176e+04],
       [ 6.64394688e+03],
       [ 1.32177745e+04],
       [ 1.47464884e+04],
       [ 9.76210317e+03],
       [ 1.87601859e+03],
       [ 5.84440368e+03],
       [ 2.57898275e+03],
       [ 5.60184617e+03],
       [-5.84302973e+02],
       [ 1.42270383e+04],
       [ 3.52589659e+03],
       [ 1.09271889e+04],
       [ 1.32922176e+04],
       [ 1.16160396e+04],
       [ 8.93443908e+03],
       [ 1.37334894e+04],
       [ 7.59275380e+02],
       [ 1.11539180e+04],
       [ 9.18403837e+03],
       [ 8.10677499e+03],
       [ 1.54684815e+04],
       [ 1.24211390e+04],
       [ 2.96319132e+04],
       [ 1.79372669e+04],
       [ 1.09168107e+04],
       [ 9.20286783e+03],
       [ 1.21754744e+04],
       [ 5.68131067e+03],
       [ 1.55205592e+04],
       [ 6.90874636e+03],
       [ 5.40250374e+03],
       [ 3.12694987e+04],
       [ 1.41473744e+04],
       [ 1.33735030e+04],
       [ 1.17701466e+04],
       [ 1.23815532e+04],
       [ 5.25886836e+03],
       [ 3.09136118e+03],
       [ 4.25664633e+03],
       [ 5.45276061e+03],
       [ 7.88759418e+01],
       [ 8.58138851e+03],
       [ 7.62753888e+03],
       [ 5.72281084e+03],
       [ 1.46009387e+04],
       [ 4.49537515e+03],
       [ 7.65694595e+03],
       [ 5.07737463e+03],
       [ 1.18161170e+03],
       [ 6.03456067e+03],
       [ 5.78707516e+03],
       [ 2.67758213e+03],
       [ 3.04508206e+04],
       [ 1.07883755e+04],
       [ 1.26290387e+04],
       [ 3.69395341e+04],
       [ 5.56388183e+03],
       [ 1.33197103e+04],
       [ 1.07958248e+03],
       [ 7.35566774e+03],
       [ 2.52672923e+04],
       [ 1.01289319e+04],
       [ 5.46485371e+03],
       [ 1.50545030e+04],
       [ 8.94117544e+03],
       [ 3.31100558e+04],
       [ 1.27396252e+04],
       [ 9.01763884e+03],
       [ 1.13563676e+04],
       [ 2.98550131e+04],
       [ 4.92326764e+03],
       [ 8.31285377e+03],
       [ 1.04565101e+04],
       [ 2.68111796e+03],
       [ 3.39114199e+04],
       [ 2.60515419e+04],
       [ 1.28263608e+04],
       [ 7.56336801e+03],
       [ 6.08299662e+03],
       [ 3.35634207e+04],
       [ 3.40257417e+04],
       [ 1.10189459e+04],
       [ 2.83798924e+04],
       [ 3.25353274e+04],
       [ 4.60798198e+03],
       [ 3.30977633e+04],
       [ 9.39656064e+03],
       [ 3.32622485e+04],
       [ 2.61035137e+04],
       [ 1.32573603e+04],
       [ 1.27642102e+04],
       [ 5.15683914e+03],
       [ 1.51168530e+04],
       [ 1.10984104e+04],
       [ 3.96234635e+03],
       [ 1.49646603e+04],
       [ 1.70388950e+04],
       [ 2.36081086e+03],
       [ 7.89051745e+03],
       [ 3.36828699e+04],
       [-2.48358083e+03],
       [ 4.86947494e+03],
       [ 1.10362599e+04],
       [ 1.43741036e+04],
       [ 9.52337435e+03],
       [ 7.88759418e+01],
       [ 3.72288127e+04],
       [ 4.27227527e+03],
       [ 1.57785164e+04],
       [ 4.92828908e+03],
       [ 2.40049012e+03],
       [ 1.07664390e+04],
       [ 1.12335820e+04],
       [ 1.56500812e+04],
       [ 8.35637428e+03],
       [ 3.84474916e+04],
       [ 9.65643212e+03],
       [ 1.15225677e+04],
       [ 4.89203966e+03],
       [ 1.18343175e+04],
       [ 2.60288712e+04],
       [ 9.95771033e+03],
       [ 6.01744613e+03],
       [ 1.04823813e+04],
       [ 2.49000349e+04],
       [ 9.98711740e+03],
       [ 1.08094247e+04],
       [ 8.67294611e+03],
       [ 1.59324239e+04],
       [ 2.83148970e+03],
       [-1.58500951e+03],
       [ 8.52747336e+02],
       [ 2.88701349e+04],
       [ 5.84568986e+03],
       [ 1.42891889e+04],
       [ 3.59680382e+03],
       [ 3.47720269e+04],
       [ 3.25938219e+03],
       [ 9.18030311e+03],
       [ 7.56838945e+03],
       [ 1.42408464e+04],
       [ 8.73701100e+03],
       [-1.22491717e+03],
       [ 7.40592461e+03],
       [ 1.22878818e+04],
       [ 1.06779885e+04],
       [ 5.68676085e+03],
       [ 2.69812352e+04],
       [ 1.75771745e+04],
       [ 1.87251457e+04],
       [ 2.75202519e+03],
       [ 5.35244631e+03],
       [ 1.12731678e+04],
       [ 6.04001085e+03],
       [ 8.19542493e+03],
       [ 5.21736820e+03],
       [ 1.37732746e+04],
       [ 2.07162576e+03],
       [ 7.94913216e+03],
       [ 3.95025325e+03],
       [ 1.98862542e+03],
       [ 9.04704591e+03],
       [ 6.40683955e+03],
       [ 1.17133951e+03],
       [ 1.17684317e+04],
       [ 9.23207547e+03],
       [ 3.87660838e+04],
       [ 1.37457819e+04],
       [ 3.11379564e+04],
       [ 2.41522640e+04],
       [ 1.31846322e+04],
       [ 8.12762478e+03],
       [ 4.42093208e+03],
       [ 5.87209583e+03],
       [ 7.75523991e+03],
       [ 1.72222096e+04],
       [ 5.52720367e+03],
       [ 1.49164661e+03],
       [ 4.06437557e+03],
       [ 1.17615893e+04],
       [ 5.39394647e+03],
       [ 9.35132522e+03],
       [ 1.10085677e+04],
       [ 9.75172499e+03],
       [ 1.19761320e+04],
       [ 3.50971560e+04],
       [ 1.01789893e+04],
       [ 1.05616464e+04],
       [ 2.91366493e+04],
       [ 1.36866160e+03],
       [ 1.32544651e+03],
       [ 1.01827246e+04],
       [ 4.56317530e+03],
       [ 7.20840309e+03],
       [ 3.28194691e+03],
       [ 7.59106015e+03],
       [ 2.34267352e+04],
       [ 1.19192322e+04],
       [ 5.86836057e+03],
       [ 3.96908271e+03],
       [ 1.74524746e+04],
       [ 7.48218858e+03],
       [ 1.53314677e+03],
       [ 9.77447267e+02],
       [ 7.90783142e+03],
       [ 8.97411834e+03],
       [ 6.27540326e+03],
       [ 9.21496093e+03],
       [ 8.74074626e+03],
       [ 1.15142098e+04],
       [ 3.51563989e+04],
       [ 5.33179593e+03],
       [ 3.86021114e+03],
       [ 1.10569103e+04],
       [ 5.96867487e+03],
       [ 7.50786039e+03],
       [ 9.73943246e+03],
       [ 9.14907513e+03],
       [ 1.03960744e+04],
       [ 6.57132473e+03],
       [ 9.64596050e+03],
       [ 2.79421565e+04],
       [ 2.25386354e+04],
       [ 1.10208603e+04],
       [ 9.03164629e+03],
       [-6.24088217e+02],
       [ 2.41591064e+04],
       [ 5.51864640e+03],
       [ 1.80157553e+03],
       [ 5.90130347e+03],
       [ 2.77013139e+04],
       [ 1.63132601e+04],
       [ 3.89634059e+04],
       [ 1.63115452e+04],
       [ 1.44658606e+04],
       [ 3.83764642e+03],
       [ 2.54109277e+04],
       [ 1.05084818e+04],
       [ 1.37703669e+04],
       [ 1.34915600e+04],
       [ 4.18051823e+03],
       [ 1.03176967e+04],
       [ 3.83315484e+04],
       [ 2.56914496e+04],
       [ 4.41591064e+03],
       [ 1.46718459e+04],
       [ 3.16991061e+04],
       [ 6.04311794e+03],
       [ 2.80701629e+04],
       [ 6.00181720e+03],
       [ 1.22188889e+04],
       [ 7.99254668e+03],
       [ 1.19106749e+04],
       [ 3.58824655e+03],
       [ 1.22566538e+04],
       [ 1.33908170e+04],
       [ 3.78385372e+03],
       [ 1.28540529e+04],
       [ 1.72845596e+04],
       [ 2.56376569e+04],
       [ 1.30790671e+04],
       [ 2.83506848e+04],
       [ 2.69171703e+04],
       [ 7.74688207e+03],
       [ 1.21546246e+04],
       [ 3.61364551e+04],
       [ 1.19675747e+04],
       [ 9.89182453e+03],
       [ 1.21321533e+04],
       [ 1.08856887e+04],
       [ 8.61413198e+03],
       [ 4.84700366e+03],
       [ 1.66640397e+03],
       [ 2.77551066e+04],
       [ 1.13601028e+04],
       [ 1.31554246e+04],
       [-6.24088217e+02],
       [ 7.92346035e+03],
       [ 4.86091767e+03],
       [ 1.34046250e+04],
       [ 1.02035744e+04],
       [ 8.12762478e+03],
       [ 3.08005347e+04],
       [ 9.74627481e+03],
       [ 3.41520411e+03],
       [ 1.16074823e+04],
       [ 1.10171250e+04],
       [ 7.54080329e+03],
       [ 1.47965459e+04],
       [ 9.68563976e+03],
       [ 1.11730529e+04],
       [ 1.24061382e+04],
       [ 6.00161777e+03],
       [ 3.19703222e+03],
       [ 4.04904983e+04],
       [ 1.29058253e+04],
       [ 1.46720454e+04],
       [ 9.19431056e+03],
       [ 5.04443174e+03],
       [ 1.05616464e+04],
       [ 4.92326764e+03],
       [ 9.61321703e+03],
       [ 1.37025668e+04],
       [ 3.60225401e+03],
       [ 3.79786117e+03],
       [ 9.41741044e+03],
       [ 4.57857491e+03],
       [ 6.06396773e+03],
       [ 8.88920365e+03],
       [ 5.20378949e+03],
       [ 2.57483493e+04],
       [ 4.22030348e+03],
       [ 4.77418208e+03],
       [ 5.44591826e+03],
       [ 9.59408216e+03],
       [ 4.91288946e+03],
       [ 1.48729033e+04],
       [ 1.65315380e+04],
       [ 2.64427562e+04],
       [ 3.53436482e+04],
       [ 2.47139736e+03],
       [ 3.68686269e+04],
       [ 3.06195411e+03],
       [ 1.57214172e+04],
       [ 7.00403923e+03],
       [ 6.72714665e+03],
       [ 3.06238630e+04],
       [ 1.39396741e+04],
       [ 1.10898532e+04],
       [ 8.50172458e+03],
       [ 2.13397572e+03],
       [ 1.54959742e+04],
       [ 3.02308278e+04],
       [-8.75203002e+02],
       [ 8.83230387e+03],
       [ 9.68808884e+03],
       [ 9.45708970e+03],
       [ 1.37440670e+04],
       [ 4.93000400e+03],
       [ 4.24597529e+03],
       [ 1.30705099e+04],
       [ 2.63353703e+04],
       [ 1.67495104e+04],
       [ 2.87871346e+04],
       [ 1.65936885e+04],
       [ 9.01581793e+03],
       [ 1.06239963e+04],
       [ 1.51205882e+04],
       [ 1.21980391e+04],
       [ 1.10861179e+04],
       [ 2.50906206e+04],
       [ 3.28833267e+04],
       [ 9.42768263e+03],
       [ 1.08544607e+04],
       [ 2.66609281e+04],
       [ 4.16651078e+03],
       [ 5.67446833e+03],
       [ 5.33351086e+03],
       [ 1.09791607e+04],
       [ 3.81671692e+04],
       [ 3.37504706e+04],
       [ 2.72929850e+04],
       [ 1.45611534e+04],
       [ 3.55893128e+04],
       [ 3.97910700e+04],
       [ 2.36081086e+03],
       [ 2.68565353e+04],
       [ 6.21123239e+03],
       [ 3.66797561e+04],
       [ 5.68131067e+03],
       [ 1.11003248e+04],
       [ 2.75202519e+03],
       [ 3.46179199e+04],
       [ 1.57574671e+04],
       [ 7.44551042e+03],
       [ 1.19554816e+04],
       [ 4.94893945e+03],
       [ 1.04718037e+04],
       [ 2.94692489e+04],
       [ 7.74688207e+03],
       [ 2.52049424e+04],
       [ 1.08318960e+04],
       [-1.49674122e+02],
       [ 3.32572270e+04],
       [ 1.17267321e+04],
       [ 7.28456108e+03],
       [ 1.14516604e+04],
       [ 2.88231845e+04],
       [ 1.10623604e+04],
       [-5.54895906e+02],
       [ 4.41591064e+03],
       [ 8.22813851e+03],
       [ 3.62792581e+03],
       [ 2.23611093e+03],
       [ 1.15225677e+04],
       [ 8.58290400e+03],
       [ 3.33129341e+04],
       [ 1.30843179e+04],
       [ 2.87672513e+03],
       [ 6.19038259e+03],
       [ 3.09717563e+04],
       [ 1.10292181e+04],
       [ 1.45186136e+03],
       [ 3.68253058e+04],
       [ 9.08854607e+03],
       [ 3.65362267e+04],
       [ 6.35506719e+03],
       [ 1.42496030e+04],
       [ 7.46305371e+03],
       [ 2.86728128e+04],
       [ 3.74426790e+03],
       [ 1.70112028e+04],
       [ 1.13495252e+04],
       [ 9.09710334e+03],
       [ 3.61204273e+04],
       [ 1.31554246e+04],
       [ 1.85328451e+04],
       [ 1.55308314e+04],
       [ 3.82435266e+04],
       [ 1.20061672e+04],
       [ 3.09612847e+04],
       [ 9.69248211e+03],
       [ 3.81326079e+03],
       [ 9.79322516e+03],
       [ 1.24419888e+04],
       [ 1.16889672e+04],
       [ 9.18575329e+03],
       [ 1.51499953e+04],
       [ 1.65259764e+01],
       [ 7.22221111e+03],
       [ 1.19052247e+04],
       [ 4.85909676e+03],
       [ 1.35257891e+04],
       [ 3.21838983e+04],
       [ 1.10068528e+04],
       [ 2.54109277e+04],
       [ 2.63320637e+04],
       [ 1.46028530e+04],
       [ 1.41058742e+04],
       [ 1.46946101e+04],
       [ 6.79131752e+03],
       [ 3.07120842e+04],
       [ 1.50026246e+04],
       [ 2.99882703e+04],
       [ 6.43806753e+03],
       [ 1.75131866e+03],
       [ 3.01013058e+04],
       [ 7.72431735e+03],
       [ 3.24986493e+04],
       [ 3.29713484e+04],
       [ 3.24106275e+04],
       [ 3.54846131e+03],
       [ 9.20951075e+03],
       [ 9.85868221e+03],
       [ 1.00096821e+04],
       [ 3.19779130e+04],
       [ 2.97718133e+04],
       [ 8.07383209e+03],
       [ 3.12418065e+04],
       [ 1.09047176e+04],
       [ 7.79191807e+03],
       [ 4.01933957e+03],
       [ 2.97424062e+04],
       [ 1.11974386e+04],
       [ 1.58907244e+04],
       [ 1.58509391e+04],
       [ 7.06830354e+03],
       [ 3.32173215e+03],
       [ 5.29181126e+03],
       [ 3.13024415e+04],
       [ 5.65190360e+03],
       [ 5.88547511e+03],
       [ 1.10377754e+04],
       [ 1.39482314e+04],
       [ 7.67032523e+03],
       [ 1.05691169e+04],
       [ 1.60448313e+04],
       [ 1.08024890e+04],
       [ 3.49295369e+03],
       [ 5.49446020e+03],
       [ 2.86536779e+04],
       [ 3.53776779e+04],
       [ 1.09565960e+04],
       [ 9.58552489e+03],
       [ 7.94057489e+03],
       [ 1.04913673e+04],
       [ 7.35375339e+03],
       [ 1.73901246e+04],
       [ 2.99766059e+04],
       [ 1.40764672e+04],
       [ 1.22395393e+04],
       [ 1.17133951e+03],
       [ 1.50459457e+04],
       [ 1.68041143e+03],
       [ 9.06416044e+03],
       [ 1.39290965e+04],
       [ 1.43515388e+04],
       [ 7.76773187e+03],
       [ 1.42391314e+04],
       [ 6.60073179e+03],
       [ 1.15536896e+04],
       [ 9.67910283e+03],
       [ 5.35082482e+03],
       [ 9.74316772e+03],
       [ 2.55641803e+03],
       [ 1.39413891e+04],
       [ 2.71223995e+03],
       [ 3.00998233e+03],
       [ 7.48892494e+03],
       [ 1.50770677e+04],
       [ 9.24436800e+03],
       [ 1.17029746e+04],
       [ 3.12644772e+04],
       [ 5.52911802e+03],
       [ 1.31506833e+03],
       [ 1.62147667e+04],
       [ 7.15814622e+03],
       [ 1.15849176e+04],
       [ 1.19277894e+04],
       [ 1.05218611e+04],
       [ 9.14736021e+03],
       [ 1.21963242e+04],
       [ 1.61071813e+04],
       [ 7.21696036e+03],
       [ 1.10189459e+04],
       [ 3.63783844e+04],
       [ 5.28325399e+03],
       [ 7.74496772e+03],
       [ 3.96665695e+04],
       [ 1.03143603e+04],
       [ 5.33179593e+03],
       [ 1.25146109e+04],
       [ 3.64706069e+03],
       [ 3.90588982e+04],
       [ 3.32328414e+04],
       [ 1.51394177e+04],
       [-6.24088217e+02],
       [ 1.35899600e+04],
       [ 3.07033275e+04],
       [ 2.94135419e+04],
       [ 1.17407395e+04],
       [ 5.29009634e+03],
       [ 1.68896869e+03],
       [ 1.52017676e+04],
       [ 3.08088956e+03],
       [ 6.90190402e+03],
       [ 2.45256790e+03],
       [ 2.95382418e+04],
       [ 3.30977633e+04],
       [ 3.48986412e+04],
       [ 1.30134107e+04],
       [ 1.88757169e+04],
       [ 7.77437479e+03],
       [ 3.89965482e+04],
       [ 8.93635343e+03],
       [ 2.99960415e+03],
       [ 1.31950104e+04],
       [ 8.21082455e+03],
       [ 3.70888191e+04],
       [ 1.11607604e+04],
       [ 7.90078964e+03],
       [ 4.39697520e+03],
       [ 2.94763236e+03],
       [ 6.21978965e+03],
       [ 1.27414461e+04],
       [ 2.91989993e+04],
       [ 1.09791607e+04],
       [ 5.82001805e+03],
       [ 2.75144634e+04],
       [ 3.10046992e+04],
       [ 1.17805248e+04],
       [ 2.94763236e+03],
       [ 1.23502317e+04],
       [ 3.43998415e+04],
       [ 3.43374915e+04],
       [ 2.96372699e+04],
       [ 2.30701817e+03],
       [ 1.20213674e+04],
       [ 7.46807514e+03],
       [ 2.32958289e+03],
       [ 3.41348919e+03],
       [ 8.45338206e+03],
       [ 9.58734580e+03],
       [ 9.71022482e+03],
       [ 6.78778169e+03],
       [ 3.86021114e+03],
       [ 9.96818195e+03],
       [ 1.43117536e+04],
       [ 9.63386740e+03],
       [ 5.90130347e+03],
       [ 1.57747811e+04],
       [ 8.70588901e+03],
       [-1.54522426e+03],
       [ 1.14829818e+04],
       [ 1.32884823e+04],
       [ 3.33540055e+04],
       [ 2.72929850e+04],
       [ 1.15207467e+04],
       [ 8.62460360e+03],
       [ 1.36711394e+04],
       [ 2.97390698e+04],
       [ 1.71096028e+04],
       [ 6.10566733e+03],
       [ 1.14867171e+04],
       [ 9.87097474e+03],
       [ 2.96404705e+04],
       [ 8.50172458e+03],
       [ 3.21074349e+04],
       [ 1.37543392e+04],
       [ 4.54061057e+03],
       [ 1.77210093e+04],
       [ 2.86624346e+04],
       [-5.61738252e+02],
       [ 2.20690412e+02],
       [ 3.28194691e+03],
       [ 6.24919672e+03],
       [ 2.67147208e+04],
       [ 4.17698240e+03],
       [ 1.08283602e+04],
       [ 7.43866808e+03],
       [ 1.20384819e+04],
       [ 2.62227634e+04],
       [ 1.50997384e+04],
       [ 3.56308130e+04],
       [ 3.13250063e+04],
       [ 6.76511098e+03],
       [ 3.40171844e+04],
       [ 1.36316596e+04],
       [ 7.18926821e+03],
       [ 7.53042511e+03],
       [ 1.01080821e+04],
       [ 9.67354666e+03],
       [ 1.21131244e+04],
       [ 8.82203167e+03],
       [ 1.25337458e+04],
       [ 7.49094528e+03],
       [ 3.39263939e+03],
       [ 3.01269776e+04],
       [ 3.16580425e+03],
       [ 8.58492434e+03],
       [ 6.75281846e+03],
       [ 3.32173215e+03],

In [24]:
# train r2_score:
from sklearn.metrics import r2_score
train_r_score = r2_score(y_train,y_train_predict)
train_r_score

0.7301346831003432

In [25]:
# cheak the model prediction:
y_test_predict = regressor.predict(x_test)
y_test_predict

array([[11565.98217656],
       [ 9995.67466779],
       [37644.41261058],
       [15975.63903696],
       [ 7029.71103416],
       [ 3565.57584859],
       [ 1079.58247626],
       [14218.48105937],
       [ 8943.19577262],
       [ 7418.01770623],
       [ 4387.98918363],
       [10283.03886615],
       [ 8963.84614274],
       [ 4308.32525176],
       [27434.79950391],
       [11398.06715433],
       [11233.38255159],
       [ 5499.71095716],
       [ 8108.68933689],
       [26269.71377852],
       [33293.37045682],
       [14072.93133078],
       [11131.35332609],
       [32313.42027672],
       [ 4313.77543409],
       [ 8648.98922835],
       [  776.38991839],
       [10420.03132531],
       [ 4112.71808596],
       [10234.69635245],
       [ 8818.4958417 ],
       [40327.83405646],
       [15913.2890715 ],
       [14107.58915266],
       [24138.25658062],
       [ 4495.37514814],
       [13055.11025749],
       [30729.62750369],
       [33058.08403097],
       [ 3837.64641584],
       [ 3480.66116194],
       [ 4197.6327726 ],
       [29889.67088563],
       [38942.75553632],
       [27715.42734059],
       [ 4724.12463985],
       [11077.76005761],
       [ 7705.18247704],
       [ 3047.94666254],
       [10653.40340009],
       [ 4931.82490635],
       [ 3081.08898846],
       [33326.31335518],
       [37971.56205321],
       [16202.47417761],
       [ 6502.13241512],
       [ 5986.21815259],
       [ 9294.42543241],
       [ 9540.48889053],
       [11707.79664633],
       [ 1938.36855669],
       [38527.15557578],
       [15539.3887063 ],
       [12165.09620221],
       [13558.93141933],
       [14230.57416006],
       [26011.75664725],
       [31811.71289351],
       [ 1200.74657591],
       [ 9893.73888561],
       [12812.35331401],
       [11894.84654271],
       [25308.79248835],
       [15890.72435031],
       [11273.16779586],
       [12234.08908603],
       [ 6981.36852047],
       [ 9976.73922119],
       [29567.64886539],
       [39242.21283537],
       [11522.5676577 ],
       [37367.42658939],
       [ 3993.46833737],
       [ 9760.28225772],
       [33958.37027919],
       [29228.40632207],
       [ 8742.56716865],
       [ 4704.9897657 ],
       [12410.76080523],
       [30450.82057476],
       [ 9637.6026621 ],
       [11545.13237889],
       [ 7689.88884593],
       [ 9313.56030656],
       [ 7729.56810597],
       [ 6766.93189229],
       [35298.21337272],
       [33409.51311831],
       [ 7303.69595248],
       [15326.46757409],
       [ 4251.42546863],
       [ 8399.58936651],
       [ 6850.13165542],
       [31678.25626561],
       [32727.39875707],
       [ 1799.66117402],
       [ 9560.9398331 ],
       [ 6221.61056266],
       [13920.53925629],
       [37228.61322248],
       [10187.74600233],
       [10849.63873761],
       [ 9933.32470233],
       [26074.10661271],
       [40132.22689065],
       [ 8179.59657178],
       [  748.89720236],
       [ 9294.42543241],
       [15613.83177245],
       [ 9365.53209485],
       [35227.50556539],
       [ 7287.66816543],
       [17109.60277174],
       [ 9081.9031553 ],
       [ 8581.18908056],
       [ 2944.0965293 ],
       [32467.52727474],
       [31105.01347579],
       [39470.76289954],
       [ 5016.739593  ],
       [ 9696.21736874],
       [ 3756.36100378],
       [ 7994.36758314],
       [ 8271.15417678],
       [31944.7706663 ],
       [29881.1136162 ],
       [30022.92808597],
       [ 9322.11757599],
       [32734.04167543],
       [ 3124.30407976],
       [ 3197.03222239],
       [10904.51818544],
       [13508.67455456],
       [12248.09653779],
       [ 5321.21833021],
       [15828.37438486],
       [15333.30992   ],
       [ 2357.27503188],
       [ -303.78112036],
       [10480.36095547],
       [ 7033.44629298],
       [31919.09885802],
       [11948.63923874],
       [ 2795.43971361],
       [ 5975.94595964],
       [ 8189.97474895],
       [ 4147.57533539],
       [ 2475.13261689],
       [11398.06715433],
       [12225.73124415],
       [ 6706.4962779 ],
       [16553.90326495],
       [11593.47489259],
       [14190.78891579],
       [ 2769.13973361],
       [ 6727.34607557],
       [23168.77802103],
       [ 7137.49585378],
       [ 4867.65403315],
       [ 5243.57473364],
       [ 6552.38927988],
       [ 4568.19673409],
       [ 9758.5673342 ],
       [ 5470.30389006],
       [ 6065.88208446],
       [ 6985.30320683],
       [ 3286.96834721],
       [ 5329.77559964],
       [37432.97708527],
       [ 1039.79723199],
       [12400.48861229],
       [ 8645.45339709],
       [13662.58212502],
       [ 5603.56109041],
       [ 4834.71113479],
       [35822.68490468],
       [ 3673.16124065],
       [ 2327.86796479],
       [14867.45309469],
       [12267.23141194],
       [34328.73481313],
       [ 5052.989006  ],
       [ 5876.91783701],
       [31570.67087355],
       [ 5728.26102133],
       [ 2267.23292284],
       [ 7850.73220563],
       [ 9575.25269664],
       [ 8349.5319293 ],
       [ 5508.26822659],
       [12762.2958768 ],
       [38580.74884426],
       [13494.6671028 ],
       [28928.94902302],
       [ 6427.68934897],
       [35670.59824196],
       [ 3153.71114686],
       [12372.79646871],
       [ 9296.4457677 ],
       [ 6485.01787626],
       [11174.76784495],
       [14031.23173544],
       [ 5082.3960731 ],
       [ 4611.51780963],
       [ 8087.83953922],
       [ 1626.6187294 ],
       [ 7426.57497566],
       [ 4142.12515305],
       [13399.37423898],
       [ 4046.83228924],
       [10473.82402134],
       [ 6959.00322683],
       [ 9458.91060759],
       [ 1924.36110493],
       [13640.01740383],
       [16429.20333403],
       [15354.15971767],
       [11077.56063006],
       [ 6020.64665785],
       [ 2525.19005411],
       [ 2321.02561888],
       [12901.00325948],
       [14538.58872854],
       [ 4578.77433882],
       [ 4204.47511851],
       [ 9843.48202085],
       [ 9613.01760561],
       [27621.84940029],
       [ 7313.96814543],
       [10095.98896978],
       [ 6559.03219824],
       [29294.49154634],
       [11484.80274872],
       [ 7208.20366111],
       [10193.19618467],
       [12144.24640454],
       [ 2442.18971853],
       [10565.38162635],
       [ 1150.48971114],
       [ 6486.30405561],
       [28722.87023671],
       [38991.09805002],
       [ 6654.52448961],
       [ 8484.61003739],
       [ 2040.50376642],
       [ -241.4311549 ],
       [10721.20354788],
       [ 4282.65344348],
       [ 4743.15352978],
       [ 2914.6894622 ],
       [ 7506.03947997],
       [33561.70576525],
       [37744.52748501],
       [14659.7528282 ],
       [ 8087.83953922],
       [15584.42470535],
       [33195.07649013],
       [ 9045.22499812],
       [33833.86977583],
       [ 3602.25400576],
       [29954.04118638],
       [ 8482.78912964],
       [13794.12440185],
       [ 3834.11058458],
       [32472.97745707],
       [ 7923.46034826],
       [11669.8323098 ],
       [ 9736.09605634],
       [ 3951.96816958],
       [13028.81027749],
       [11718.1748235 ],
       [ 8049.87520269],
       [12834.9180352 ],
       [ 2360.81086315],
       [10196.73201593],
       [ 5674.66775285],
       [11431.20948025],
       [31115.39165297],
       [ 9984.01031127],
       [  719.49013527],
       [  324.7399724 ],
       [39281.99807964],
       [ 9190.57529916],
       [ 6829.28185775],
       [13814.97419952],
       [13020.25300806],
       [27403.6775133 ],
       [ 7549.36055551],
       [ 7180.71094509],
       [12497.49639962],
       [ 2578.98275014],
       [ 4106.0751676 ],
       [24642.07774246],
       [26193.3563613 ],
       [13390.617542  ],
       [ 2845.49715083],
       [ 5281.53907017],
       [ 9748.18915703],
       [12052.48937199],
       [22910.82088976],
       [30622.24153918],
       [10215.86689008],
       [23747.04224901],
       [ 2618.76799441],
       [11519.4605706 ],
       [ 7729.56810597],
       [ 7919.72508944],
       [  387.08993785],
       [ 7488.72551356],
       [35062.92694688],
       [ 5622.69596456],
       [ 5797.45333269],
       [   56.31122063],
       [11060.4460912 ],
       [ 6799.87479065],
       [10116.63933989],
       [39094.94818327],
       [27235.65650685],
       [11112.41787949],
       [35714.01276082],
       [14651.19555877],
       [ 6747.99644569],
       [11308.02504529],
       [ 7276.20323646],
       [36565.43430785],
       [ 6126.31769884],
       [10890.51073368],
       [ 1131.55426454],
       [24387.65644246],
       [ 1862.01113948],
       [34861.96304207],
       [11301.28868361],
       [ 1626.6187294 ],
       [31401.46967198],
       [ 6879.53872252],
       [ 5722.81083899],
       [37988.67659207],
       [ 2578.98275014],
       [ 9232.2748945 ],
       [ 2566.88964945],
       [13049.85950271],
       [ 1375.50394405],
       [11240.85306922],
       [ 7160.06057497],
       [36063.52749709],
       [ 7537.06802726],
       [30395.31295521],
       [29502.19181283],
       [ 7313.96814543],
       [10305.80301489],
       [ 1618.06145997],
       [ 2760.58246418],
       [ 3567.59618388],
       [12455.99623184],
       [37270.31281782],
       [10139.20406108],
       [  696.92541408],
       [10975.42542033],
       [ 4736.21774054],
       [10286.57469741],
       [ 4992.35396406],
       [ 7134.18933913],
       [ 4538.789667  ],
       [27933.59922758],
       [ 3944.69707951],
       [ -842.26010407],
       [33371.54878178],
       [12980.46776379],
       [36238.48429277],
       [10397.16119235],
       [ 7367.76084146],
       [ -232.87388547],
       [ 2236.11093223],
       [11884.57434976],
       [ 6219.78965492],
       [ 2681.11795987],
       [11605.76742083],
       [ 8302.58157918],
       [ 7230.7683823 ],
       [ 5052.989006  ],
       [ 3009.98232602],
       [32040.26295768],
       [ 3415.20410939],
       [ 9013.90357995],
       [ 4923.26763692],
       [12549.57417214],
       [15006.16047737],
       [ 7617.1607033 ],
       [26823.79180512],
       [14427.89624938],
       [17544.23162221],
       [12109.38915511]])

In [26]:
#test r2_score:
test_r_score = r2_score(y_test,y_test_predict)
test_r_score

0.78913454847886

In [27]:
print("Training R²:", train_r_score)
print("Test R²:", test_r_score)

Training R²: 0.7301346831003432
Test R²: 0.78913454847886

In [28]:
# Model Deployement:
# Save the model name:
filename = 'Linear_regression_Assign.sav'

In [29]:
import pickle
pickle.dump(regressor,open(filename,'wb'))

In [30]:
loaded_model = pickle.load(open('Linear_regression_Assign.sav','rb'))
loaded_model

LinearRegression()

In [31]:
# Final checking:
new_data = pd.DataFrame({
    'age': [40],
    'bmi': [30.2],
    'children': [2],
    'sex_male': [1],
    'smoker_yes': [1]
})

new_data_scaled = sc.transform(new_data)
result = loaded_model.predict(new_data_scaled)
result

array([[32441.7460126]])