#### SVMR ####

In [147]:
# import the libraries:
import pandas as pd

In [148]:
# Read dataset:
dataset = pd.read_csv('Startups.csv')
dataset.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [149]:
# In this dataset categorical input is there. so, we have to change it. it is nominal one so we go for one hot encoding:
dataset = pd.get_dummies(dataset,drop_first = True)
dataset.head()

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,False,True
1,162597.70,151377.59,443898.53,191792.06,False,False
2,153441.51,101145.55,407934.54,191050.39,True,False
3,144372.41,118671.85,383199.62,182901.99,False,True
4,142107.34,91391.77,366168.42,166187.94,True,False

In [150]:
# split input and output:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [151]:
independent = dataset[['R&D Spend', 'Administration', 'Marketing Spend',
       'State_Florida', 'State_New York']]

In [152]:
dependent = dataset[['Profit']]

In [153]:
# split Train and Test data:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [154]:
# Standardise the value:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [155]:
# Model creation:
from sklearn.svm import SVR
regressor = SVR(kernel='rbf',C=1000)
regressor

SVR(C=1000)

In [156]:
# train the model:
regressor.fit(x_train,y_train)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=1000)

In [157]:
regressor.intercept_

array([108599.21691873])

In [158]:
regressor.n_support_

array([35], dtype=int32)

In [159]:
regressor.support_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34], dtype=int32)

In [160]:
# test the nodel:
y_pred = regressor.predict(x_test)
y_pred

array([108850.4890541 , 109950.89932949, 109625.28827269, 106457.61477211,
       110497.62736423, 111965.89425661, 106745.59361645, 107722.43659459,
       109550.70495554, 110127.86030555, 107421.65926298, 107704.29927075,
       108618.72535073, 108096.72836328, 109925.96848141])

In [161]:
# Evaluate the model quality:
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)
r_score

0.0067683444800727965

In [162]:
# It is poor model